# Generated by Django 3.1.3 on 2020-12-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_hotel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hotel',
            new_name='image_upload',
        ),
        migrations.RenameField(
            model_name='image_upload',
            old_name='hotel_Main_Img',
            new_name='Img',
        ),
        migrations.AlterField(
            model_name='mirna',
            name='location',
            field=models.TextField(max_length=20),
        ),
    ]
