# Generated by Django 3.1.3 on 2020-12-17 13:51

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20201217_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_upload',
            name='name',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Mubaarak', 'Mubaarak'), ('Nabeel', 'Nabeel'), ('Abdul-Mujeeb', 'Abdul-Mujeeb')], default='DEFAULT VALUE', max_length=28),
        ),
    ]
