# Generated by Django 3.1.3 on 2020-12-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20201217_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_upload',
            name='name',
            field=models.CharField(blank=True, choices=[('Mubaarak', 'Mubaarak'), ('Nabeel', 'Nabeel'), ('Abdul-Mujeeb', 'Abdul-Mujeeb')], max_length=50, null=True),
        ),
    ]
