# Generated by Django 3.1.3 on 2020-12-19 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20201217_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_upload',
            name='name',
            field=models.CharField(default=2, max_length=50),
        ),
    ]
