# Generated by Django 3.1.3 on 2020-12-23 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0010_auto_20201219_1821'),
    ]

    operations = [
        migrations.DeleteModel(
            name='miRNA',
        ),
        migrations.DeleteModel(
            name='Tutorial',
        ),
        migrations.AddField(
            model_name='image_upload',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='image_upload',
            name='name',
            field=models.CharField(blank=True, choices=[('Mubaarak', 'Mubaarak'), ('Nabeel', 'Nabeel'), ('Abdul-Mujeeb', 'Abdul-Mujeeb')], max_length=50),
        ),
    ]
