# Generated by Django 3.1.4 on 2021-01-24 22:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20201223_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='image_upload',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
