# Generated by Django 3.1.4 on 2021-01-25 16:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_login_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login_time',
            name='time',
            field=models.TimeField(verbose_name=datetime.datetime(2021, 1, 25, 16, 24, 55, 399188, tzinfo=utc)),
        ),
    ]
