# Generated by Django 3.1.4 on 2021-02-01 15:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210125_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login_time',
            name='time',
        ),
        migrations.AddField(
            model_name='login_time',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
